Add concurrency rules

diff --git a/.github/workflows/micromamba.yml b/.github/workflows/micromamba.yml
--- a/.github/workflows/micromamba.yml
+++ b/.github/workflows/micromamba.yml
@@ -24,7 +24,7 @@ jobs:
       matrix:
         ob_branch: [dev, reduce_install_scope, main]
         micromamba_version: ['2.0.5-0', '1.5.12-0']
-      fail-fast: true
+      fail-fast: false
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
@@ -35,7 +35,7 @@ jobs:
         with:
           cache-environment: true
           micromamba-version: ${{ matrix.micromamba_version }}
-          environment-name: test-env
+          environment-name: test-env-${{matrix.ob_branch }}-${{ matrix.micromamba_version }}
           create-args: >-
             python=3.12
             pip
@@ -56,18 +56,25 @@ jobs:
       - name: Run benchmark
         shell: bash -l {0}
         run: |
-          date
-          echo "y" | ob run benchmark -b Clustering.yaml --local --cores 10 --continue-on-error
-          date
+          env
+          output=$( echo "y" | ob run benchmark -b Clustering.yaml --local --cores 10 2>&1 )
+          status=$?
+          if echo "$output" | grep -v 'Error'; then
+             status=0
+          fi
+          sh -c "exit $status"
         if: matrix.ob_branch == 'dev' || matrix.ob_branch == 'reduce_install_scope'
 
       - name: Run benchmark
         shell: bash -l {0}
-        continue-on-error: true
         run: |
-          date
-          ob run benchmark -b Clustering.yaml --local --threads 10
-          date
+          env
+          output=$( ob run benchmark -b Clustering.yaml --local --threads 10  2>&1 )
+          status=$?
+          if echo "$output" | grep -v 'Error'; then
+             status=0
+          fi
+          sh -c "exit $status"
         if: matrix.ob_branch == 'main'
 
   # upload-artifact:
diff --git a/.github/workflows/miniconda_miniforge.yml b/.github/workflows/miniconda_miniforge.yml
--- a/.github/workflows/miniconda_miniforge.yml
+++ b/.github/workflows/miniconda_miniforge.yml
@@ -1,6 +1,6 @@
 name: clustbench_miniforge
 concurrency:
-  group: ${{ github.head_ref || github.run_id }}
+  group: ${{ github.head_ref || github.run_id  }}
   cancel-in-progress: true
 
 on:
@@ -33,7 +33,7 @@ jobs:
         with:
           miniforge-variant: Miniforge3
           use-mamba: true
-          activate-environment: omnibenchmark-env
+          activate-environment: test-env-${{matrix.ob_branch }}
           python-version: "3.12"
           auto-update-conda: true
           channels: conda-forge
@@ -66,17 +66,25 @@ jobs:
       - name: Run benchmark
         shell: bash -l {0}
         run: |
-          date
-          echo "y" | ob run benchmark -b Clustering.yaml --local --cores 10 --continue-on-error
-          date
+          env
+          output=$( echo "y" | ob run benchmark -b Clustering.yaml --local --cores 10  2>&1 )
+          status=$?
+          if echo "$output" | grep -v 'Error'; then
+             status=0
+          fi
+          sh -c "exit $status"
         if: matrix.ob_branch == 'dev' || matrix.ob_branch == 'reduce_install_scope'
 
       - name: Run benchmark
         shell: bash -l {0}
         run: |
-          date
-          ob run benchmark -b Clustering.yaml --local --threads 10
-          date
+          env
+          output=$( ob run benchmark -b Clustering.yaml --local --threads 10  2>&1 )
+          status=$?
+          if echo "$output" | grep -v 'Error'; then
+             status=0
+          fi
+          sh -c "exit $status"
         if: matrix.ob_branch == 'main'
 
   # upload-artifact:
